name: Continuous Deployment
on:
    push:
        tags:
            - '*'
concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout
            - run: |
                mkdir dist
                cp index.html dist
            - uses: actions/upload-artifact
              with:
                  name: dist
                  path: dist
    deploy:
        needs:
            - build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact
              with:
                  name: dist
            - uses: actions/upload-pages-artifact
              path: dist
